[package]
name = "microbio-domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.64"

[dev-dependencies]
pretty_assertions_sorted = "1.2.1"
